### PR TITLE
Fix stopping PFCP timers

### LINKED ISSUE #80: Another crash due to PFCP response timers issue
Debug build (`v1.1.1`):
```
pfcp_msg_pool_elt_at_index:261: ERROR: accessing a PFCP msg that was freed at: /src/vpp/src/plugins/upf/upf_pfcp_server.c:473 response_expired                    
/src/vpp/src/plugins/upf/upf_pfcp_server.h:262 (pfcp_msg_pool_elt_at_index) assertion `0' fails
...
[New LWP 7]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/vpp -c /etc/vpp/startup.conf'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f9c0c7dbfb7 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#0  0x00007f9c0c7dbfb7 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9c0c7dd921 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00000000004071f5 in os_exit (code=1) at /src/vpp/src/vpp/vnet/main.c:395
#3  0x00007f9c0e314707 in unix_signal_handler (signum=6, si=0x7f9c10090bb0, uc=0x7f9c10090a80) at /src/vpp/src/vlib/unix/main.c:187
#4  <signal handler called>
#5  0x00007f9c0c7dbfb7 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f9c0c7dd921 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000000000407193 in os_panic () at /src/vpp/src/vpp/vnet/main.c:371
#8  0x00007f9c0d6bc619 in debugger () at /src/vpp/src/vppinfra/error.c:84
#9  0x00007f9c0d6bc397 in _clib_error (how_to_die=2, function_name=0x0, line_number=0, fmt=0x7f9bc417e027 "%s:%d (%s) assertion `%s' fails") at /src/vpp/src/vppinfra/error.c:143
#10 0x00007f9bc4126614 in pfcp_msg_pool_elt_at_index (psm=0x7f9bc43bb460 <pfcp_server_main>, index=6414) at /src/vpp/src/plugins/upf/upf_pfcp_server.h:262
#11 0x00007f9bc41254b2 in response_expired (id=6414) at /src/vpp/src/plugins/upf/upf_pfcp_server.c:467
#12 0x00007f9bc41166ac in pfcp_process (vm=0x7f9c0e547b80 <vlib_global_main>, rt=0x7f9bcca6a0c0, f=0x0) at /src/vpp/src/plugins/upf/upf_pfcp_server.c:1252
#13 0x00007f9c0e28deed in vlib_process_bootstrap (_a=140307136063496) at /src/vpp/src/vlib/main.c:1454
#14 0x00007f9c0d6e07a4 in clib_calljmp () at /src/vpp/src/vppinfra/longjmp.S:123
#15 0x00007f9bcd012800 in ?? ()
#16 0x00007f9c0e28d92f in vlib_process_startup (vm=0x1afee8f1e8, p=0x874ad741c34756, f=0x95) at /src/vpp/src/vlib/main.c:1479
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

Release build (`v1.1.4`; due to lack of ASSERTs in the release build, the issue is not caught early enough, leads to crash in another place later):
```
warning: core file may not match specified executable file.
[New LWP 8]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/vpp -c /etc/vpp/startup.conf'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f1ea4a7d921 in __GI_abort () at abort.c:79
#2  0x0000561a8cc38715 in os_exit (code=<optimized out>) at /src/vpp/src/vpp/vnet/main.c:395
#3  0x00007f1ea6568135 in unix_signal_handler (signum=11, si=<optimized out>, uc=<optimized out>) at /src/vpp/src/vlib/unix/main.c:184
#4  <signal handler called>
#5  upf_pfcp_send_data (msg=0x7f1ce2867800) at /src/vpp/src/plugins/upf/upf_pfcp_server.c:83
#6  0x00007f1e5c4fcb08 in upf_pfcp_server_rx_msg (msg=0x7f1cecaa7180) at /src/vpp/src/plugins/upf/upf_pfcp_server.c:272
#7  pfcp_process (vm=<optimized out>, rt=<optimized out>, f=<optimized out>) at /src/vpp/src/plugins/upf/upf_pfcp_server.c:1162
#8  0x00007f1ea65081a7 in vlib_process_bootstrap (_a=<optimized out>) at /src/vpp/src/vlib/main.c:1454
#9  0x00007f1ea594eec4 in clib_calljmp () from /usr/lib/x86_64-linux-gnu/libvppinfra.so.20.09
#10 0x00007f1e6528a550 in ?? ()
#11 0x00007f1ea64fdcd2 in vlib_process_startup (vm=0x7f1ea67826c0 <vlib_global_main>, p=0x7f1e64ce20c0, f=0x0) at /src/vpp/src/vlib/main.c:1479
#12 dispatch_process (vm=0x7f1ea67826c0 <vlib_global_main>, p=0x7f1e64ce20c0, f=0x0, last_time_stamp=<optimized out>) at /src/vpp/src/vlib/main.c:1535
Backtrace stopped: Cannot access memory at address 0x7f1ea899c0b8```

### PR DESCRIPTION
**Pull request by ivan4th**
This is a "resurrection" of #7.

After we've reverted #7 and replaced it with #12, we first had the problem resurface in #44, which we mitigated to a degree by #49, but then we were hit by #80.

Fixes #80.

### CODE REVIEW

File: upf/upf_pfcp_server.c [hunk 1]
```diff
@@ -491,7 +491,7 @@ restart_response_timer (pfcp_msg_t * msg)
   upf_debug ("Msg Seq No: %u, idx %u\n", msg->seq_no, id);
 
   if (msg->timer != ~0)
```
Comment (RoadRunnr) [inline upf/upf_pfcp_server.c:493]: you can also drop the `if`

Comment (ivan4th) [reply upf/upf_pfcp_server.c]: done

**Review by sergeymatov — COMMENTED** [review]
lgtm

**Review by sergeymatov — APPROVED** [review]

**Review by sergeymatov — APPROVED** [review]
