### PR TITLE
Reclassify flows upon session modification

### LINKED ISSUE #14: Flows may have stale PDR ids after session modification
Previous report: travelping/vpp#85

quay.io/travelping/upf:fix-2009-traffic-timer_v20.09-upfbase-9-g9a520fa75_debug

The result of having stale PDRs is this crash:
```
/src/vpp/src/plugins/upf/upf_input.c:152 (upf_input) assertion `(((upf_buffer_opaque_t *)((u8 *)((b)->opaque2) + ((uword) & (((vnet_buffer_opaque_t *) 0)->unused))))->gtpu.pdr_idx) < vec_len (active->pdr)' fails
```

### PR DESCRIPTION
**Pull request by ivan4th**
This adds generation id to the session which is checked against the
flow. If the generation id does not match, the flow is re-classified.

In order to enable flow re-classification in case of app detection,
the URI that was extracted by ADF code is now stored in the flow.

Formely, the traffic on flows for modified sessions could result
in crashes such as this:

```
/src/vpp/src/plugins/upf/upf_input.c:152 (upf_input) assertion `(((upf_buffer_opaque_t *)((u8 *)((b)->opaque2) + ((uword) & (((vnet_buffer_opaque_t *) 0)->unused))))->gtpu.pdr_idx) < vec_len (active->pdr)' fails
```

Fixes #14.

### CODE REVIEW

File: upf/upf_adf.c [hunk 1]
```diff
@@ -365,38 +365,61 @@ upf_application_detection (vlib_main_t * vm, u8 * p,
...
+      upf_debug ("Using port %u, instead of %u", port,
+		 clib_net_to_host_u16 (flow->
+				       key.port[FT_ORIGIN ^ flow->is_reverse]));
 
-    case ADR_OK:
-      break;
+      if (*p == TLS_HANDSHAKE)
+	r = upf_adr_try_tls (port, p, &uri);
+      else
+	r = upf_adr_try_http (port, p, &uri);
```
Comment (sergeymatov) [inline upf/upf_adf.c:408]: indentation to be fixed

Comment (ivan4th) [reply upf/upf_adf.c:408]: It's a GitHub display artifact ...
